/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   map_gen.c                                          :+:    :+:            */
/*                                                     +:+                    */
/*   By: dvan-boc <marvin@codam.nl>                   +#+                     */
/*                                                   +#+                      */
/*   Created: 2020/01/15 11:26:06 by dvan-boc      #+#    #+#                 */
/*   Updated: 2020/01/15 11:26:07 by dvan-boc      ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

/*
** The Virtual Machine 'filler_vm'
** Prints the map upon starting the project.
** Prints players 'token' on every turn.
*/

#include "../libft/includes/libft.h"
#include "../includes/filler.h"

#define stdout 0

/**
 * Gets the current map.
 * @return
 */
char *get_map()
{
	return (read_stdout("Plateau", ' ', 8))
}

/*
** Allocates a linear allocated memory area to store the map.
** @param map Represents a pointer to a linear allocated 2D Array.
** @param col Represents the column size.
** @param row Represents the line size.
** @return
*/
static char		*alloc_map(char *map, int row, int col)
{
	map = malloc(sizeof(char[col][row]));
	if (!map)
		return (NULL);
	return (map);
}

/*
** Reads file contents
** @param identifier represents the a phrase to look for, i.e. "Plateau ", or "piece ".
** @param delimiter represents a space in both cases.
** @param len for strncmp
** @param readType: 0 = Read Map, 1 = Read Token.
** @return A pointer to the read map;
** { Expression statements are within scope }
**/
char	*read_stdout(char *identifier, char delimiter, int len)
{
	char	*map;
	char	*line;
	int		col;
	int		row;

	map = NULL;
	while (get_next_line(stdout, &line))
	{
		if (ft_strncmp(line, identifier, len))
		{
			while (*line != ':')
			{
				*line == delimiter && row == 0 ? row : col = {
						ft_atoi(line);
				};
				line++;
			}
		}
	}
	if (identifier == "Plateau" || identifier == "Piece")
		map = alloc_map(map, row col);
	return (fill_stdout(map, line, row, col));
}

/**
**
** Fills the map by copying a line read from the standard input.
** Works for both Map & Piece filling.
** @param map A pointer to a 2D Array
** @param line Represents a pointer the current position
** @param row represents the row size
** @param col represents the col size
** @return a pointer to a 2D Array generated by alloc_map
*/
char	*fill_stdout(char *map, char *line, int row, int col)
{
	int index;

	index = 0;
	while (get_next_line(stdout, &line))
	{
		while (index != col)
		{
			if (*line == ('.' || 'O' || 'X' || 'o' || 'x' || '*'))
				ft_strcpy(*map[index], line);
			else
				line++;
			index++;
		}
	}
	return (map);
}