/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   map_gen.c                                          :+:    :+:            */
/*                                                     +:+                    */
/*   By: dvan-boc <marvin@codam.nl>                   +#+                     */
/*                                                   +#+                      */
/*   Created: 2020/01/15 11:26:06 by dvan-boc      #+#    #+#                 */
/*   Updated: 2020/01/15 11:26:07 by dvan-boc      ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#include "../libft/includes/libft.h"
#include "../includes/filler.h"
#include "../includes/player.h"
#include <stdlib.h>

/**
 * stdout represents the standard output's file descriptor.
 * For information about File Desciptors head to the man pages 'fd' & 'fcntl'.
 */
#define stdout 0

/**
** Initializes the information read from @stdout
** to the right variable, both Map & Piece.
** @param   map A pointer to a 2D Array
** @param   line Represents a pointer the current position on the read buffer.
** @return  a pointer to a 2D Array generated by alloc_map
*/
static struct s_map	*init_output(struct s_map *map, char *line)
{
	int index;

	index = 0;
	while (get_next_line(stdout, &line) && index < map->x)
	{
			while (line)
			{
				if (*line == '.' || *line == 'O' || *line =='X' ||
					*line == 'o' || *line == 'x' || *line == '*')
				{
					ft_strcpy(&map->board[index], line);
					break;
				}
				else
					line++;
			}
			index++;
	}
	return (map);
}

/**
** reads from the standard output the current state of the game
** @param   map represents a pointer to a specific element to assign to.
** @param   identifier represents a string to look for
            i.e. "Plateau " or "piece ".
** @param   delimiter represents a space in both cases.
** @param   len for strncmp
** @return  A pointer to the read map;
** @TODO:	The 'char *line' variable represents a pointer to the line read
**          from the stdout buffer
** 			the pointer's position is however incremented and passed to
**          init_output leaving the pointer
** 			on an invalid index that has already been read.
** 			NOTE: Just noticed init_output re-uses the pointer, and should
**          still only free the allocated memory space.
**/

static struct s_map 	*read_stdout(struct s_map *map, char *identifier,
        char delimiter, int len)
{
	char	*line;

	while (get_next_line(stdout, &line))
	{
		if (ft_strncmp(line, identifier, len))
		{
			while (*line != ':')
			{
				*line == delimiter ? *map = (struct s_map) {
					.x = ft_atoi(line)
				} : (struct s_map) { .y = ft_atoi(line) };
				line++;
			}
		}
	}
	if ((ft_strcmp(identifier, "Plateau") || ft_strcmp(identifier, "Piece") == 0))
	{
		map->board = malloc(sizeof(char[map->x]));
		while (index < map->x)
		{
			map->board[index] = ft_memalloc(sizeof(char[map->y + 1]));
			index++;
		}
	}
	return (init_output(map, line));
}

/**
 * encapsulates the read_stdout function
 * and returns a game_map read from 'Standard Output'
 * @return a Filled game_map
 */
struct s_map	*get_board(struct s_map *board)
{
	return (read_stdout(board, "Plateau", ' ', 8));
}

/**
 * encapsulates the read_stdout function
 * and returns a game_piece read from 'Standard Output'
 * @return a Filled game_piece
 */
struct s_map	*get_piece(struct s_map *piece)
{
	return (read_stdout(piece, "Piece", ' ', 5));
}